eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'false'
    register-with-eureka: 'false'
  instance:
    prefer-ip-address: 'true'
spring:
  application:
    name: discovery-service-app
server:
  port: '8761'
