spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
      - id: booking-service-route
        uri: lb://booking-service
        predicates:
         - Path=/booking/**
      - id: payment-service-route
        uri: lb://payment-service
        predicates:
         - Path=/payment/**
  application:
    name: springcloudapigateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: '8080'
 
